# -*- coding: utf-8 -*-
"""agent_mcp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiInHE34iLRK1FwwMBBWb9cwG0VvEnR_
"""



import os
from dotenv import load_dotenv

load_dotenv()

try:
    google_api_key= os.getenv("GOOGLE_API_KEY")
    if not google_api_key:
        raise ValueError("GOOGLE_API_KEY must be set in the .env file.")
    
    os.environ["GOOGLE_API_KEY"]  = google_api_key
    
    print("✅ Setup and authentication complete.")
except Exception as e:
    print(
        f"🔑 Authentication Error: Please make sure you have added 'GOOGLE_API_KEY' to your Kaggle secrets. Details: {e}"
    )

import uuid
from google.genai import types

from google.adk.agents import LlmAgent
from google.adk.models.google_llm import Gemini
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService

from google.adk.tools.mcp_tool.mcp_toolset import McpToolset
from google.adk.tools.tool_context import ToolContext
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from mcp import StdioServerParameters
from google.adk.runners import InMemoryRunner

from google.adk.apps.app import App, ResumabilityConfig
from google.adk.tools.function_tool import FunctionTool

import base64
import tempfile
import subprocess

print("✅ imported successfully.")

retry_config = types.HttpRetryOptions(
    attempts=5,  # Maximum retry attempts
    exp_base=7,  # Delay multiplier
    initial_delay=1,
    http_status_codes=[429, 500, 503, 504],  # Retry on these HTTP errors
)

# MCP integration with Everything Server
mcp_image_server = McpToolset(
    connection_params=StdioConnectionParams(
        server_params=StdioServerParameters(
            command="npx",  # Run MCP server via npx
            args=[
                "-y",  # Argument for npx to auto-confirm install
                "@modelcontextprotocol/server-everything",
            ],
        ),
        timeout=30,
    ),
    tool_filter=["getTinyImage"],
)

print("✅ MCP Tool created")

mcp_agent = LlmAgent(
    name="mcp_agent",
    model=Gemini(model="gemini-2.5-flash-lite", retry_options=retry_config),
    instruction="Use the getTinyImage tool to retrieve and display images. This tool returns a small test image.",
    tools=[mcp_image_server]
)


runner = InMemoryRunner(agent=mcp_agent)

async def test_image_mcp():
   try:
       result = await runner.run_debug("Get a tiny image", verbose=True)
       print(f"result: {result}")

   finally:
       # Clean up MCP connections
       await mcp_image_server.close()


# Main execution
def main():
    """Run the MCP agent test."""
    import asyncio
    import sys

    # Check if running in Jupyter
    try:
        ipython = __builtins__.get_ipython()
        in_notebook = ipython is not None
    except (ImportError, NameError):
        in_notebook = False

    if in_notebook:
        print("⚠️  WARNING: MCP STDIO servers have issues in Jupyter notebooks.")
        print("The subprocess-based STDIO connection may fail with 'fileno' errors.")
        print("\nRECOMMENDATION: Run this script from terminal instead:")
        print("  python agent_mcp.py")
        print("\nAttempting to run anyway with nest_asyncio...")

        try:
            import nest_asyncio
            nest_asyncio.apply()
        except ImportError:
            print("Installing nest_asyncio...")
            import subprocess
            subprocess.check_call([sys.executable, "-m", "pip", "install", "nest_asyncio"])
            import nest_asyncio
            nest_asyncio.apply()

    # Run the async function
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(test_image_mcp())
    finally:
        loop.close()


if __name__ == "__main__":
    main()
